#! /bin/sh

# Settings

bspc config border_width        0
bspc config window_gap          5
bspc config split_ratio         0.50

bspc config single_monocle                false
bspc config borderless_monocle            false
bspc config gapless_monocle               false
bspc config pointer_follows_monitor       true
bspc config focus_follows_pointer         true
bspc config auto_cancel                   true
bspc config honor_size_hints              true
bspc config click_to_focus                true

# Setup monitors
i=1
for monitor in $(bspc query -M); do
    bspc monitor $monitor \
        -n "$i" \
        -d {One,Two,Three,Four,Five,Six,Seven,Eight,Nine,Ten}
    let i++
done
unset i

# Adopt any ophan windows
bspc control --adopt-orphans

# nice composting
compton --config "$HOME/.config/compton.conf" --xrender-sync-fence &

# automount flash disks
udiskie --tray &

# turn off hardware beep
xset b off &

# switch caps and escape keys
setxkbmap -option caps:escape &
      
# save my eyes
redshift &

# sync thing
#syncthing-gtk &

# wallaper
sh .fehbg &


# Always float chrome chat windows
bspc rule -a crx_nckgahadagoaajjgafhacjanaoiihapd state=floating
bspc rule -a mpv state=floating
