#! /bin/sh

# TODO: find a way to use `sleep` less

bspc config border_width        0
bspc config window_gap          2
bspc config focus_follows_pointer true
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
# bspc config focus_by_distance   true
bspc config remove_disabled_monitor true

bspc monitor -d 01 02 03 04 05 06 07 08 09 10
bspc rule -a feh state=fullscreen
bspc rule -a mpv state=fullscreen
bspc rule -a URxvtQuake sticky=on state=floating
bspc rule -a tint2 state=floating manage=off # needed with R675M, window hints previously worked

# cursor
xsetroot -cursor_name left_ptr &

# wallpaper
hsetroot -fill ~/elephant.jpg &

# nice composting
compton --config "$HOME/.config/compton.conf" --xrender-sync-fence &

# automound flash disks
udiskie --tray &

nm-applet &
# numlockx on &

# turn off hardware beep
xset b off &

# tint2 volume icon
volumeicon &

# switch caps and escape keys
setxkbmap -option caps:escape &

# /usr/local/bin/conkystart.sh

# desktop 10 is the sys monitor workspace
# bspc rule -a URxvtDesktop desktop=^1
# bspc rule -a htop desktop=^1
# bspc config -d ^1 split_ratio 0.80
# conky -c ~/.config/conky/bspwm.conky &
# urxvt -name URxvtDesktop &
# sleep to allow terminal to spawn first
# sleep 2 && urxvt -bg '[0]#000000' -name htop -e htop &

# seems to help if tint2 is started after compton is fully up and running
#   previous sleep command should allow for that

# desktop panel
tint2 &
      
# save my eyes
redshift &

# google drive sync
insync start &


# seems as if split_ratio takes effect for all desktops
#   this resets it
#   sleep is required to allow desktop 10 windows to spawn
# sleep 2 && bspc config -d focused split_ratio 0.50

# autostart.sh &
